version: '3.3'

services:
 jenkins:
  hostname: jenkins
  build: ./jenkins
  container_name: server-tools-jenkins
  hostname: server-tools-jenkins
  restart: always
  logging:
    options:
      max-size: 50m
  ports:
    - "18080:8080"
    - "50000:50000"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker
    - /var/platform/data/jenkins-home:/var/jenkins_home
  environment:
    - JAVA_OPTS="-Djava.awt.headless=true"
    - VIRTUAL_HOST=server-jenkins.localhost
  networks:
    rests_net:
      ipv4_address: 169.10.2.1

networks:
  rests_net:
    external:
      name: network_rests_net